/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.cesba;

/**
 *
 * @author Eduardo
 */
public class CalculadoraCientificaCESBA extends javax.swing.JFrame {

    float num1, num2;
    String signo;
    boolean decimal = false;
    /**
     * Creates new form DemoCal
     */
    public CalculadoraCientificaCESBA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta_1 = new javax.swing.JLabel();
        txt_output = new javax.swing.JLabel();
        btn_C = new javax.swing.JButton();
        btn_X = new javax.swing.JButton();
        btn_divicion = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btc_suma = new javax.swing.JButton();
        btc_igual = new javax.swing.JButton();
        btc_1 = new javax.swing.JButton();
        btc_2 = new javax.swing.JButton();
        btc_3 = new javax.swing.JButton();
        btc_4 = new javax.swing.JButton();
        btc_5 = new javax.swing.JButton();
        btc_6 = new javax.swing.JButton();
        btc_7 = new javax.swing.JButton();
        btc_8 = new javax.swing.JButton();
        btc_9 = new javax.swing.JButton();
        btc_0 = new javax.swing.JButton();
        btc_punto = new javax.swing.JButton();
        borraruno = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        btc_Pi = new javax.swing.JButton();
        btc_cuadrado = new javax.swing.JButton();
        btc_raiz_cubica = new javax.swing.JButton();
        btc_raiz = new javax.swing.JButton();
        btc_sin = new javax.swing.JButton();
        btc_cos = new javax.swing.JButton();
        btc_tan = new javax.swing.JButton();
        btc_log = new javax.swing.JButton();
        btc_factorial = new javax.swing.JButton();
        btc_euler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        etiqueta_1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        etiqueta_1.setForeground(new java.awt.Color(51, 51, 255));
        etiqueta_1.setText("CALCULADORA CIENTIFICA CESBA");

        txt_output.setBackground(new java.awt.Color(204, 204, 204));
        txt_output.setFont(new java.awt.Font("Book Antiqua", 0, 48)); // NOI18N
        txt_output.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_output.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_C.setText("C");
        btn_C.setBorder(null);
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        btn_X.setText("x");
        btn_X.setBorder(null);
        btn_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XActionPerformed(evt);
            }
        });

        btn_divicion.setText("/");
        btn_divicion.setBorder(null);
        btn_divicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divicionActionPerformed(evt);
            }
        });

        btn_resta.setText("-");
        btn_resta.setBorder(null);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btc_suma.setText("+");
        btc_suma.setBorder(null);
        btc_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_sumaActionPerformed(evt);
            }
        });

        btc_igual.setText("=");
        btc_igual.setBorder(null);
        btc_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_igualActionPerformed(evt);
            }
        });

        btc_1.setText("1");
        btc_1.setBorder(null);
        btc_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_1ActionPerformed(evt);
            }
        });

        btc_2.setText("2");
        btc_2.setBorder(null);
        btc_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_2ActionPerformed(evt);
            }
        });

        btc_3.setText("3");
        btc_3.setBorder(null);
        btc_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_3ActionPerformed(evt);
            }
        });

        btc_4.setText("4");
        btc_4.setBorder(null);
        btc_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_4ActionPerformed(evt);
            }
        });

        btc_5.setText("5");
        btc_5.setBorder(null);
        btc_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_5ActionPerformed(evt);
            }
        });

        btc_6.setText("6");
        btc_6.setBorder(null);
        btc_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_6ActionPerformed(evt);
            }
        });

        btc_7.setText("7");
        btc_7.setBorder(null);
        btc_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_7ActionPerformed(evt);
            }
        });

        btc_8.setText("8");
        btc_8.setBorder(null);
        btc_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_8ActionPerformed(evt);
            }
        });

        btc_9.setText("9");
        btc_9.setBorder(null);
        btc_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_9ActionPerformed(evt);
            }
        });

        btc_0.setText("0");
        btc_0.setBorder(null);
        btc_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_0ActionPerformed(evt);
            }
        });

        btc_punto.setText(".");
        btc_punto.setBorder(null);
        btc_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_puntoActionPerformed(evt);
            }
        });

        borraruno.setText("CE");
        borraruno.setBorder(null);
        borraruno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarunoActionPerformed(evt);
            }
        });

        porcentaje.setText("%");
        porcentaje.setBorder(null);
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        btc_Pi.setText("π");
        btc_Pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_PiActionPerformed(evt);
            }
        });

        btc_cuadrado.setText("x²");
        btc_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_cuadradoActionPerformed(evt);
            }
        });

        btc_raiz_cubica.setText("³√");
        btc_raiz_cubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_raiz_cubicaActionPerformed(evt);
            }
        });

        btc_raiz.setText("√");
        btc_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_raizActionPerformed(evt);
            }
        });

        btc_sin.setText("sin");
        btc_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_sinActionPerformed(evt);
            }
        });

        btc_cos.setText("cos");
        btc_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_cosActionPerformed(evt);
            }
        });

        btc_tan.setText("tan");
        btc_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_tanActionPerformed(evt);
            }
        });

        btc_log.setText("log");
        btc_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_logActionPerformed(evt);
            }
        });

        btc_factorial.setText("x!");
        btc_factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_factorialActionPerformed(evt);
            }
        });

        btc_euler.setText("e");
        btc_euler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btc_eulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btc_cos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_cuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_raiz_cubica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_Pi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_log, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btc_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btc_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btc_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borraruno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btc_0, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btc_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btc_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btc_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_divicion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_X, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btc_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(etiqueta_1)
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(etiqueta_1)
                .addGap(18, 18, 18)
                .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_divicion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borraruno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_raiz_cubica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btc_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btc_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btc_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_X, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_log, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btc_0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_Pi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btc_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        txt_output.setText("");
        decimal=false;
        
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        signo = "*";//Cambiar el signo
        txt_output.setText("");
    }//GEN-LAST:event_btn_XActionPerformed

    private void btc_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_2ActionPerformed
        txt_output.setText(txt_output.getText() + "2");
    }//GEN-LAST:event_btc_2ActionPerformed

    private void btc_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_8ActionPerformed
        txt_output.setText(txt_output.getText() + "8");
    }//GEN-LAST:event_btc_8ActionPerformed

    private void btc_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_1ActionPerformed
        txt_output.setText(txt_output.getText() + "1");
    }//GEN-LAST:event_btc_1ActionPerformed

    private void btc_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_puntoActionPerformed
        if(decimal==false){
        txt_output.setText(txt_output.getText() + ".");
        decimal=true;
        }
    }//GEN-LAST:event_btc_puntoActionPerformed

    private void btc_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_0ActionPerformed
        txt_output.setText(txt_output.getText() + "0");
    }//GEN-LAST:event_btc_0ActionPerformed

    private void btc_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_5ActionPerformed
        txt_output.setText(txt_output.getText() + "5");
    }//GEN-LAST:event_btc_5ActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        signo = "-";//Cambiar el signo
        txt_output.setText("");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btc_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_3ActionPerformed
        txt_output.setText(txt_output.getText() + "3");
    }//GEN-LAST:event_btc_3ActionPerformed

    private void btc_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_4ActionPerformed
        txt_output.setText(txt_output.getText() + "4");
    }//GEN-LAST:event_btc_4ActionPerformed

    private void btc_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_6ActionPerformed
        txt_output.setText(txt_output.getText() + "6");
    }//GEN-LAST:event_btc_6ActionPerformed

    private void btc_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_7ActionPerformed
        txt_output.setText(txt_output.getText() + "7");
    }//GEN-LAST:event_btc_7ActionPerformed

    private void btc_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_9ActionPerformed
        txt_output.setText(txt_output.getText() + "9");
    }//GEN-LAST:event_btc_9ActionPerformed

    private void btn_divicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divicionActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        signo = "/";//Cambiar el signo
        txt_output.setText("");
    }//GEN-LAST:event_btn_divicionActionPerformed

    private void btc_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_sumaActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        signo = "+";//Cambiar el signo
        txt_output.setText("");
    }//GEN-LAST:event_btc_sumaActionPerformed

    private void btc_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_igualActionPerformed
        num2 = Float.parseFloat(txt_output.getText());
        
        switch (signo){
        
            case"+":
                txt_output.setText(Float.toString(num1 + num2));
                break;
            case"-":
                txt_output.setText(Float.toString(num1 - num2));
                break;
            case"*":
                txt_output.setText(Float.toString(num1 * num2));
                break;
            case"/":
                txt_output.setText(Float.toString(num1 / num2));
                break;
            case"%":
                txt_output.setText(Float.toString(num1 * num2 /100));
                break;
            
        }
    }//GEN-LAST:event_btc_igualActionPerformed

    private void borrarunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarunoActionPerformed
        String texto = txt_output.getText().substring(0,txt_output.getText().length()-1);
        txt_output.setText(texto);
    }//GEN-LAST:event_borrarunoActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        signo="%";
        txt_output.setText("");
    }//GEN-LAST:event_porcentajeActionPerformed

    private void btc_PiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_PiActionPerformed
      txt_output.setText(Float.toString((float)Math.PI));
    }//GEN-LAST:event_btc_PiActionPerformed

    private void btc_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_cuadradoActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(Float.toString(num1 * num1));
    }//GEN-LAST:event_btc_cuadradoActionPerformed

    private void btc_raiz_cubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_raiz_cubicaActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf(Math.cbrt((double)num1)));

    }//GEN-LAST:event_btc_raiz_cubicaActionPerformed

    private void btc_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_raizActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf((float)Math.sqrt((double)num1)));

    }//GEN-LAST:event_btc_raizActionPerformed

    private void btc_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_sinActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf(Math.sin(num1))); 
    }//GEN-LAST:event_btc_sinActionPerformed

    private void btc_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_cosActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf(Math.cos(num1)));
    }//GEN-LAST:event_btc_cosActionPerformed

    private void btc_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_tanActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf(Math.tan(num1)));
    }//GEN-LAST:event_btc_tanActionPerformed

    private void btc_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_logActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
        txt_output.setText(String.valueOf(Math.log(num1)));
    }//GEN-LAST:event_btc_logActionPerformed

    private void btc_factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_factorialActionPerformed
        num1 = Float.parseFloat(txt_output.getText());
    int factorial = 1;
    for (int i = 1; i <= num1; i++) {
        factorial *= i;
    }
    txt_output.setText(Integer.toString(factorial));
    }//GEN-LAST:event_btc_factorialActionPerformed

    private void btc_eulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btc_eulerActionPerformed
        txt_output.setText(Float.toString((float)Math.E));
    }//GEN-LAST:event_btc_eulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaCESBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaCESBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaCESBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaCESBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraCientificaCESBA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borraruno;
    private javax.swing.JButton btc_0;
    private javax.swing.JButton btc_1;
    private javax.swing.JButton btc_2;
    private javax.swing.JButton btc_3;
    private javax.swing.JButton btc_4;
    private javax.swing.JButton btc_5;
    private javax.swing.JButton btc_6;
    private javax.swing.JButton btc_7;
    private javax.swing.JButton btc_8;
    private javax.swing.JButton btc_9;
    private javax.swing.JButton btc_Pi;
    private javax.swing.JButton btc_cos;
    private javax.swing.JButton btc_cuadrado;
    private javax.swing.JButton btc_euler;
    private javax.swing.JButton btc_factorial;
    private javax.swing.JButton btc_igual;
    private javax.swing.JButton btc_log;
    private javax.swing.JButton btc_punto;
    private javax.swing.JButton btc_raiz;
    private javax.swing.JButton btc_raiz_cubica;
    private javax.swing.JButton btc_sin;
    private javax.swing.JButton btc_suma;
    private javax.swing.JButton btc_tan;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_X;
    private javax.swing.JButton btn_divicion;
    private javax.swing.JButton btn_resta;
    private javax.swing.JLabel etiqueta_1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton porcentaje;
    private javax.swing.JLabel txt_output;
    // End of variables declaration//GEN-END:variables
}
